#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
# ./run <task> <args>

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

function default {
  help
}

function auth {
  docker run --rm --entrypoint htpasswd httpd:2 -Bbn $1 $2 > traefik.auth
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
